### ISSUE TITLE
没有代码？？

### ISSUE THREAD

**Issue by zzjviva** [msAndroid/MobileSafer#1]
没有代码？？

**Comment by msAndroid** [comment]
有啊...已经完成了欢迎界面和主界面，以及进入主界面前查询更新，其它模块还没写完(持续更新)

**Comment by zzjviva** [comment]
就是只有界面。。没有功能的代码。。

**Comment by msAndroid** [comment]
还没写完。。。。。一个模块一个模块来写的

在 2015-10-19 15:11:46，"zzjviva" <notifications@github.com> 写道：


就是只有界面。。没有功能的代码。。
